FROM alpine:3.23
RUN apk add --no-cache ca-certificates tzdata
RUN addgroup -S appgroup && adduser -S appuser -G appgroup
COPY simple-wol /usr/local/bin/simple-wol
RUN mkdir -p /data && chown appuser:appgroup /data
ENV DATA_DIR=/data
EXPOSE 8080
USER appuser
CMD ["simple-wol"]
